name: send mail

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world"
      
      